apiVersion: config.openshift.io/v1
kind: Image
metadata:
  name: cluster
spec:
  registrySources:
    blockedRegistries:
      - "the-blocked-repo.io"
      - "chart-only-repo.io"
  additionalTrustedCA:
    name: registry-certs
